# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Derive the logarithm of the likelihood of a sample point from a multivariate normal distribution
#' 
#' @param X Vector, a vector of numeric values
#' @param mean Vector, the mean of multivariate normal distribution
#' @param Sigma Matrix, the variance-covariance matrix of multivariate normal distribution 
#' @return Returns the logarithm of the likelihood of X from the multivariate normal distribution 
#' with mean \code{mean} and variance \code{Sigma}
#'
#' @keywords internal
#'
logdmvnorm <- function(X, mean, Sigma) {
    .Call(`_scsbuildr_logdmvnorm`, X, mean, Sigma)
}

